### ISSUE TITLE
Models size

### ISSUE THREAD

**Issue by spdd** [ProGamerGov/Torch-Models#1]
Hi @ProGamerGov ! Great work! Thanks for your model. I solved issue :)

**Comment by ProGamerGov** [comment]
Sorry for taking so long to reply. I was able to achieve the model size by using the "continue from checkpoint" feature, on a pre-trained model that was trained on another style.

**Comment by spdd** [comment]
Thanks @ProGamerGov ! By the way of models what about "finetuned models" (e.x. flame style) I noticed that one of the models flame style has only 500 iterations and quality of styled images are very good. Are you retrain last layers of pre-trained models or by "continue from checkpoint"?

**Comment by ProGamerGov** [comment]
@spdd They are all made from the "continue from checkpoint" option, except for the "Fire_Style_22000_Iterations" model.

**Comment by spdd** [comment]
Thanks bro!
