### ISSUE TITLE
How many iterations might not be necessary?

### ISSUE THREAD

**Issue by jsxyhelu** [ProGamerGov/Torch-Models#7]
Hi! your result is great!
I want to get the same result but threse is some problem.
My question is how many iterations did you use to get these result?
thanks.

**Comment by ProGamerGov** [comment]
The names I gave each model contain how many iterations I used to get them.

My iteration count is low because I used existing models a starting point: https://github.com/ProGamerGov/Torch-Models/issues/2. I found that pretrained models could be easily trained with a different style.

**Comment by jsxyhelu** [comment]
thanks~
